# Generated by Django 2.1.2 on 2018-12-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('reson', models.TextField()),
                ('status', models.CharField(max_length=1)),
                ('date_to_meet', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
