# Generated by Django 2.1.2 on 2018-12-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_person', '0002_auto_20181212_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
