# Generated by Django 2.1.2 on 2018-12-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_person', '0003_auto_20181213_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactperson',
            name='user',
        ),
    ]
